### PR TITLE
Fsync it

### PR DESCRIPTION
**Pull request by automata**
Following same pattern from [noflo-ccv/SCDDetect](https://github.com/noflo/noflo-ccv/blob/master/components/SCDDetect.coffee).

### CODE REVIEW

**Comment by automata** [comment]
@jonnor maybe this can solve the random `libPNG read` issues we were having.

**Comment by jonnor** [comment]
Why is the .js file in spec/ removed?

**Comment by automata** [comment]
That js file was there because of a typo on `.gitignore`, js files in `spec/` should be ignored, so I fixed the typo and removed it.

**Comment by automata** [comment]
@jonnor :point_up:

**Comment by jonnor** [comment]
gmr-saliency.js and testutils.js still exists though...

**Comment by automata** [comment]
@jonnor ah those files... nice catch ;-) tks. If it looks good, please merge.

**Pull request merged**
